### ISSUE TITLE
Kernel not starting behind proxy

### ISSUE THREAD

**Issue by sangnie** [almond-sh/almond#211] opened 2018-08-26 22:14 UTC
There are a lot of problems that I faced while even downloading the kernel, as are documented in other issues and questions. I managed to work around them and set the kernel up, but now I am unable to start a scala kernel in the notebook.

`Error getting scaladex infos:
  download error: Caught java.net.ConnectException: Connection refused (Connection refused)`

I tried adding the following options to kernel.json, but they made no difference: 
`"env": {
    "JVM_OPT": "-Dhttp.proxyHost=10.10.78.22 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=10.10.78.22 -Dhttps.proxyPort=3128"
  }`

I added the options in argv itself, which at least changed the error, but I am unable to do any more progress. Are there any other settings I can try to make this work?

```[I 03:37:14.694 NotebookApp] Kernel started: 5690964b-6249-4628-be5a-49c11b162a23
Error getting scaladex infos:
  download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.0 302 Moved Temporarily" (Unable to tunnel through proxy. Proxy returns "HTTP/1.0 302 Moved Temporarily")```

**Comment by alexarchambault** [comment] 2018-10-03 14:32
Closing as a duplicate of https://github.com/almond-sh/almond/issues/157.

**Closed by alexarchambault** 2018-10-03 14:32 UTC
