### ISSUE TITLE
cannot not import akka

### ISSUE THREAD

**Issue by konfer** [almond-sh/almond#187] opened 2018-04-03 14:19 UTC
Since the version of Scala is 2.11, i have to use the akka to import the actor . But when I run the code of “import akka.actor.{ActorRef,ActorSystem,Props}” the Error of “compilation Failed”  occur , so can anyone meet this error and can solve it, thank you

**Comment by alexarchambault** [comment] 2018-10-03 14:23
Duplicate of https://github.com/almond-sh/almond/issues/160.

**Closed by alexarchambault** 2018-10-03 14:23 UTC
