### ISSUE TITLE
Standalone bootstrap doesn't work on generate-launcher.sh

### ISSUE THREAD

**Issue by maclockard** [almond-sh/almond#122] opened 2016-12-14 01:33 UTC
I added the option to make a standalone launcher (-s) in generate-launcher.sh, however, the resulting launcher still downloads JARs on its initial run.

**Comment by alexarchambault** [comment] 2016-12-14 09:16
The `generate-launcher.sh` script was a deprecated script from the previous version (`0.3.x`), I just updated it. Note that passing it the `-s` option makes the corresponding kernel fail to start for now (because of the way the classpath is handled by Ammonite, the underlying scala interpreter, which seems to be fine with the in-memory classpath of the standalone launcher). It should be fix-able though.

**Comment by maclockard** [comment] 2016-12-14 17:39
Okay thanks! just wondering, would there be any potential issues using a launcher generated by the deprecated script?

**Comment by alexarchambault** [comment] 2018-10-03 13:34
Closing as a duplicate of https://github.com/almond-sh/almond/issues/94.

**Closed by alexarchambault** 2018-10-03 13:34 UTC
