### ISSUE TITLE
Can't define type of var

### ISSUE THREAD

**Issue by lucaspg96** [almond-sh/almond#358] opened 2019-04-24 15:28 UTC
I'm making some class notes using this kernel and I found the following issue:

If I try the following code (which was working at this kernel when it was named jupyter-scala), I get an error:

```
var x: Any = 1
x = 1.5
x = true
x = 'c'
x = "string"

---

cmd2.sc:4: type mismatch;
 found   : Double(1.5)
 required: Int
val res2_1 = x = 1.5
                 ^cmd2.sc:5: type mismatch;
 found   : Boolean(true)
 required: Int
val res2_2 = x = true
                 ^cmd2.sc:7: type mismatch;
 found   : String("string")
 required: Int
val res2_4 = x = "string"
                 ^Compilation Failed
```

I thought that the problem may be related to the Any type, so I made another test:
```
var i: Int
i = 10

---

cmd2.sc:117: class Helper needs to be abstract, since variable inteiro is not defined
(Note that variables need to be initialized to be defined)
final class Helper extends java.io.Serializable{
            ^Compilation Failed
```

Also, if I try something like initializing a var with null, the type is ignored:
```
var i: Int = null
i = 10

---

cmd2.sc:4: type mismatch;
 found   : Int(10)
 required: Null
val res2_1 = i = 10
                 ^Compilation Failed
```

I do not know what is causing this, because, inside the project sbt execution I can correctly perform those actions.

**Comment by alexarchambault** [comment] 2019-04-24 16:08
Thanks for the report!

That seems to be a regression in the current master. The latest release (`0.4.0`) seems fine. If you are running the kernel from sources, just check out `0.4.0` with `git checkout v0.4.0` before running or installing the kernel.

**Comment by alexarchambault** [comment] 2019-04-24 16:10
As a workaround, putting the type ascription with the value works fine, like
```scala
var x = 1: Any
x = 1.5
x = true
x = 'c'
x = "string"
```

**Comment by lucaspg96** [comment] 2019-04-24 16:44
Thank you @alexarchambault, it worked perfectly for me!

**Comment by alexarchambault** [comment] 2019-07-16 11:24
Closing this, this should be fine with `0.6.0`.

**Closed by alexarchambault** 2019-07-16 11:24 UTC
